version: '3.8'

services:
  antink:
    build: .
    container_name: antink
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./it24_host:/original
      - ./antink_mount:/antink_mount
      - ./antink-logs:/var/log
    privileged: true
