version: "3"
services:
  antink-server:
    build: ./server
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - it24_host:/original
      - antink_mount:/antink_mount
      - antink-logs:/var/log

  antink-logger:
    build: ./logger
    volumes:
      - antink-logs:/var/log
    command: tail -F /var/log/it24.log

volumes:
  it24_host:
  antink_mount:
  antink-logs:
